import { existsSync, mkdirSync, readdirSync, rmSync, statSync } from "node:fs";
import { basename, join, relative, resolve } from "node:path";
import { Glob } from "bun";
import { packageVersion, paths, sourceLinkBase } from "./config";
import { rewriteDestinations } from "./markdown";

// Human titles for generated example pages, keyed by the source file stem.
const EXAMPLE_TITLES: Record<string, string> = {
	err: "Err",
	flow: "flow",
	format_dt: "dtStamp",
	logger: "Logger",
	outcome: "Outcome",
	test: "flow test helpers",
};

const EXAMPLE_SUMMARIES: Record<string, string> = {
	err: "Error creation, wrapping, codes, metadata, and serialization.",
	flow: "Boundaries, the callback protocol, transformations, pipelines, collections, serialization, and input protection.",
	format_dt: "Compact, sortable date and time stamps.",
	logger: "Log levels, transports, child loggers, and Err integration.",
	outcome:
		"Mapping, piping, combinators, and error handling (deprecated tier).",
	test: "Asserting on result tuples with expectOk and expectErr.",
};

export interface GenerateOptions {
	/** Release tag used for source citations, e.g. "v0.7.0". */
	tag: string;
	/** Print each written file. */
	verbose?: boolean;
}

export interface GenerateResult {
	apiFiles: string[];
	exampleFiles: string[];
}

function exampleStem(file: string): string {
	return basename(file).replace(/\.examples\.test\.ts$/, "");
}

function exampleTitle(stem: string): string {
	return EXAMPLE_TITLES[stem] ?? stem;
}

/**
 * Rewrites TypeDoc's generated destinations so the published Markdown is
 * self-contained: example references point at generated example pages, and
 * implementation citations become release-tag-pinned GitHub URLs.
 */
export function normalizeApiMarkdown(
	source: string,
	options: { blobBase: string },
): string {
	return rewriteDestinations(source, (destination) => {
		const value = destination.value;

		const media = /^_media\/(.+)\.examples\.test\.ts$/.exec(value);
		if (media) return `../examples/${media[1]}.md`;

		const example = /^\.\.\/\.\.\/src\/.*\/(.+)\.examples\.test\.ts$/.exec(
			value,
		);
		if (example) return `../examples/${example[1]}.md`;

		const src = /^\.\.\/\.\.\/(src\/.+)$/.exec(value);
		if (src) return `${options.blobBase}${src[1]}`;

		return null;
	});
}

function exampleMarkdown(
	stem: string,
	relSourcePath: string,
	body: string,
	blobBase: string,
): string {
	const title = exampleTitle(stem);
	const summary = EXAMPLE_SUMMARIES[stem];
	const lines = [
		`# ${title} examples`,
		"",
		...(summary ? [summary, ""] : []),
		`Generated from [\`${relSourcePath}\`](${blobBase}${relSourcePath}).`,
		"These examples are executable — they run as part of the library's test",
		"suite, so every line below is verified against the released code.",
		"",
		"```ts",
		body.replace(/\s*$/, ""),
		"```",
		"",
	];
	return lines.join("\n");
}

function exampleIndexMarkdown(stems: { stem: string; file: string }[]): string {
	const lines = [
		"# Examples",
		"",
		"Executable examples for each module, generated from the library's",
		"`*.examples.test.ts` files. They are regenerated by `bun run docs:generate`;",
		"do not edit them by hand.",
		"",
	];
	for (const { stem, file } of stems) {
		const summary = EXAMPLE_SUMMARIES[stem];
		lines.push(
			`- [${exampleTitle(stem)}](${file})${summary ? ` — ${summary}` : ""}`,
		);
	}
	lines.push("");
	return lines.join("\n");
}

async function runTypedoc(outDir: string): Promise<void> {
	const proc = Bun.spawn(["bunx", "typedoc", "--out", outDir], {
		cwd: paths.repoRoot,
		stdout: "pipe",
		stderr: "pipe",
	});
	const [out, err, code] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
		proc.exited,
	]);
	if (code !== 0) {
		throw new Error(`typedoc failed (exit ${code}):\n${out}\n${err}`);
	}
}

function listMarkdown(dir: string): string[] {
	const out: string[] = [];
	const walk = (current: string): void => {
		for (const name of readdirSync(current).sort()) {
			const full = join(current, name);
			if (statSync(full).isDirectory()) walk(full);
			else out.push(full);
		}
	};
	if (existsSync(dir)) walk(dir);
	return out;
}

/**
 * Regenerates `docs/api` and `docs/examples` from source. Both directories are
 * fully generator-owned: they are rebuilt in a staging directory and swapped
 * in, so a removed source entry cannot leave an obsolete Markdown file behind.
 */
export async function generateDocs(
	options: GenerateOptions,
): Promise<GenerateResult> {
	const blobBase = sourceLinkBase(options.tag);
	const staging = resolve(paths.buildDir, "docs-generate");
	rmSync(staging, { recursive: true, force: true });
	mkdirSync(staging, { recursive: true });

	const apiStaging = join(staging, "api");
	await runTypedoc(apiStaging);

	// TypeDoc copies `@see` link targets into `_media/`; the normalizer maps
	// them onto generated example pages, so the copies are never published.
	rmSync(join(apiStaging, "_media"), { recursive: true, force: true });

	const apiFiles: string[] = [];
	for (const file of listMarkdown(apiStaging)) {
		if (!file.endsWith(".md")) continue;
		const text = await Bun.file(file).text();
		await Bun.write(file, normalizeApiMarkdown(text, { blobBase }));
		apiFiles.push(relative(apiStaging, file));
	}

	const exampleStaging = join(staging, "examples");
	mkdirSync(exampleStaging, { recursive: true });
	const glob = new Glob("src/**/*.examples.test.ts");
	const sources: string[] = [];
	for await (const file of glob.scan({ cwd: paths.repoRoot })) {
		sources.push(file);
	}
	sources.sort();

	const index: { stem: string; file: string }[] = [];
	const exampleFiles: string[] = [];
	for (const relSourcePath of sources) {
		const stem = exampleStem(relSourcePath);
		const body = await Bun.file(resolve(paths.repoRoot, relSourcePath)).text();
		const outName = `${stem}.md`;
		await Bun.write(
			join(exampleStaging, outName),
			exampleMarkdown(stem, relSourcePath, body, blobBase),
		);
		index.push({ stem, file: outName });
		exampleFiles.push(outName);
	}
	await Bun.write(
		join(exampleStaging, "README.md"),
		exampleIndexMarkdown(index),
	);
	exampleFiles.push("README.md");

	const apiOut = join(paths.docsDir, "api");
	const examplesOut = join(paths.docsDir, "examples");
	rmSync(apiOut, { recursive: true, force: true });
	rmSync(examplesOut, { recursive: true, force: true });
	await copyTree(apiStaging, apiOut);
	await copyTree(exampleStaging, examplesOut);
	rmSync(staging, { recursive: true, force: true });

	if (options.verbose) {
		console.log(
			`Generated ${apiFiles.length} API page(s) and ${exampleFiles.length} example page(s).`,
		);
	}

	return { apiFiles: apiFiles.sort(), exampleFiles: exampleFiles.sort() };
}

export async function copyTree(from: string, to: string): Promise<void> {
	mkdirSync(to, { recursive: true });
	for (const name of readdirSync(from).sort()) {
		const source = join(from, name);
		const target = join(to, name);
		if (statSync(source).isDirectory()) {
			await copyTree(source, target);
			continue;
		}
		await Bun.write(target, Bun.file(source));
	}
}

export async function releaseTag(): Promise<string> {
	return `v${await packageVersion()}`;
}
